### ISSUE TITLE
Microsoft security alert

### ISSUE THREAD

**Issue by Tioxbew** [prrvchr/mDriveOOo#11]
Hi,

I've received a security message from Microsoft about 6 h after my first connection with the extension.

It is detected as a unsual activity from a windows PC located in China and using Edge browser... I'm on Arch Linux, in France.

This activity can be linked with my first connection through 
extension?
![Screenshot_20230823_194905902_Vivaldi Browser Snapshot_1](https://github.com/prrvchr/mDriveOOo/assets/76651255/5de34662-ce35-493c-95eb-10ae5fdeb91d)

**Comment by prrvchr** [comment]
No, I don't see the connection. mDriveOOO uses OAuth2 tokens provided by the OAuth2OOo extension and all connections are made under SSL.

But if your computer has been corrupted it may be a good idea to revoke the tokens in order to request new ones from Microsoft.

To do this, go to: **Tools -> Options -> Internet -> OAuth2 protocol**
In url chose vnd-microsoft and launch the wizard: in this window you can delete used tokens.

**Comment by prrvchr** [comment]
I allow myself to close this issue and remind you that all my extensions do neither more nor less than what you are able to do with your browser, but much faster...
