### ISSUE TITLE
Impossible to really modify OneDrive file through LibreOffice

### ISSUE THREAD

**Issue by Tioxbew** [prrvchr/mDriveOOo#13]
Hi,

I can open a file located on OneDrive and modify it in LibreOffice but the modifications made are not really effective on the OneDrive file, they are only visible when I open the OneDrive file with LibreOffice. For example, after opening the file in LibreOffice for the first time, the changes actually made to the OneDrive file (using Word online, for example) are not visible on the LibreOffice document (even after waiting a few minutes, then opening the file in LibreOffice). 
In fact, I have the impression that the extension makes a local copy of the online file at the first opening, then associates this local copy with the online file of the same name. In the end, all you do is open and modify this local copy.
I believe that for the changes to be saved and for the whole thing to work properly, it should be possible to make a remote backup, using a service in libreoffice...

(Confirmed on last update)

**Comment by prrvchr** [comment]
To be able to answer this question I must first explain what the mDriveOOo extension is able to do and what it is not able to do...
It uses Microsoft's onedrive Graph API which allows:

- Get the contents (metadata) of a oneDrive drive for a given account.
- Get the contents (metadata) of shared files for a given account.
- Know the changes for some time on the content of a oneDrive drive.
- Download a file.
- Upload a file.

mDriveOOo uses the Graph API as follows:

- During the first connection, it obtains the contents of the user's OneDrive drive as well as the content of the shared files.
- When opening a file if it has not already been downloaded then the file will be downloaded before being opened.
- When saving a file, saving the file is done locally and the replicator is started.
- At each replication, local changes are updated on the Graph servers, and remote changes obtained through the Graph API are updated locally.
- A data replication is automatically launched every 10 minutes.

Looking at what the Graph API offers and how mDriveOOo uses it, we can see that it is impossible to share files (simultaneous modification on the same file), but in the best case, only to alter alternatively on the server side or on the mDriveOOo side.

As for shared files, we can see that we are not able to obtain the changes that have occurred on these files.
Under these conditions, **anyone sharing files is prohibited from modifying them**, and will **only use them for consultation purposes**, in order to maintain **consistent operation on these shared files**.

**Comment by Tioxbew** [comment]
It is clear ! Thx
